version: '3.4'
services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - database_volume:/var/lib/mysql
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password

  passbolt:
    image: passbolt/passbolt:2.1.0-debian
    tty: true
    depends_on:
      - database
    environment:
      - DATASOURCES_DEFAULT_PORT=3306
      - DATASOURCES_DEFAULT_HOST=database
      - DATASOURCES_DEFAULT_DATABASE=${MYSQL_DATABASE}
      - DATASOURCES_DEFAULT_USERNAME=${MYSQL_USER}
      - DATASOURCES_DEFAULT_PASSWORD=${MYSQL_PASSWORD}
      - PASSBOLT_KEY_NAME=${PASSBOLT_KEY_NAME}
      - PASSBOLT_KEY_EMAIL=${PASSBOLT_KEY_EMAIL}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=80
      - PASSBOLT_SSL_FORCE=false
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - APP_FULL_BASE_URL=https://${LETSENCRYPT_HOST}
      - EMAIL_TRANSPORT_DEFAULT_HOST=${EMAIL_TRANSPORT_DEFAULT_HOST}
      - EMAIL_TRANSPORT_DEFAULT_PORT=${EMAIL_TRANSPORT_DEFAULT_PORT}
      - EMAIL_TRANSPORT_DEFAULT_TLS=${EMAIL_TRANSPORT_DEFAULT_TLS}
      - EMAIL_DEFAULT_FROM=${EMAIL_DEFAULT_FROM}
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=${EMAIL_TRANSPORT_DEFAULT_USERNAME}
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=${EMAIL_TRANSPORT_DEFAULT_PASSWORD}
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public
      - ./scripts/wait-for.sh:/usr/bin/wait-for.sh
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "database:3306", "--", "/docker-entrypoint.sh"]
    networks:
      - nginxproxy
      - default

networks:
  nginxproxy:
    external:
      name: ${NGINXPROXYNETWORK}

volumes:
  images_volume:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/www/passbolt/webroot/img/public
  gpg_volume:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/www/passbolt/config/gpg
  database_volume:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/lib/mysql
